quest = gg.alert(" √ WARNING...!!!After activating this function, it is required that each start a new game to activate the patch, a patch is useful for improving sensitivity. \n √ When using this function an error will occur for a while, wait until the value is found", "PATCH", "ACTIVATE CHEAT", "NO", nil)
    if quest == 0 then
      os.exit()
    end
    if quest == 1 then
r = gg.getListItems()
print('removeListItems: ', gg.removeListItems(r))
gg.searchNumber("1;10000D;100000", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("1", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(20)
gg.editAll("0.001", gg.TYPE_FLOAT)
gg.clearResults()
gg.toast("Function Ok")
    end
    if quest == 2 then
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber("30;0.3;80;25;220::", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("0.3", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
t = gg.getResults(20)
r = gg.addListItems(t)
gg.editAll("400", gg.TYPE_FLOAT)
gg.clearResults()
gg.toast("30%")
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber("1;10000D;100000", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("1", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
t = gg.getResults(20)
r = gg.addListItems(t)
gg.editAll("0.001", gg.TYPE_FLOAT)
gg.clearResults()
gg.toast("60%")
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber("0.00999999978;3;1,077,936,128D::", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("3", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
t = gg.getResults(30)
r = gg.addListItems(t)
gg.editAll("3000", gg.TYPE_FLOAT)
gg.clearResults()
gg.toast("No Recoil V3 Ok")
end